spring:
  datasource:
    url: jdbc:mysql://localhost:33306/db1
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
  sql:
    init:
      schema-locations: optional:classpath*:db/migration/schema.sql
      mode: always
