spring:
  datasource:
    url: jdbc:mysql://localhost:33306/db1
    username: root
    password: root
  sql:
    init:
      schema-locations: optional:classpath*:db/migration/schema.sql
      mode: always

logging:
  level:
    org.springframework.jdbc: debug

